# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
FROM jeanblanchard/java:8
COPY target/comd-delivery-api-swarm.jar comd-delivery-api-swarm.jar
CMD java -jar comd-delivery-api-swarm.jar
